//! Signaldefinitionen für die strukturbasierte Tätigkeitsklassifikation.

pub(crate) const CODE_EXTENSIONS: &[&str] = &[
    ".rs", ".ts", ".tsx", ".js", ".jsx", ".mjs", ".cjs", ".py", ".go", ".java", ".kt", ".kts",
    ".swift", ".c", ".cpp", ".h", ".hpp", ".cs", ".rb", ".php", ".sql", ".toml", ".yaml", ".yml",
    ".json", ".md", ".mdx", ".vue", ".svelte", ".scss", ".css", ".less", ".html", ".htm", ".xml",
    ".sh", ".bash", ".zsh", ".ps1", ".bat", ".wasm",
];

pub(crate) const CODE_FILENAMES: &[&str] = &[
    "cargo.toml",
    "cargo.lock",
    "package.json",
    "package-lock.json",
    "go.mod",
    "go.sum",
    "dockerfile",
    "makefile",
    "cmakelists.txt",
    "tsconfig.json",
    "vite.config",
    "tauri.conf.json",
];

pub(crate) const DEV_WORKFLOW_PHRASES: &[&str] = &[
    "pull request",
    "merge request",
    "code review",
    "ci/cd",
    "continuous integration",
    "build failed",
    "test failed",
    "test suite",
    "stack trace",
    "compiler error",
    "debug console",
    "git merge",
    "git rebase",
    "git commit",
    "localhost",
    "127.0.0.1",
    "::1",
];

pub(crate) const DEV_URL_PATH_MARKERS: &[&str] = &[
    "/pull/",
    "/pulls/",
    "/merge_requests/",
    "/merge-request/",
    "/issues/",
    "/commit/",
    "/commits/",
    "/tree/",
    "/blob/",
    "/compare/",
    "/actions/",
    "/pipelines/",
    "/runs/",
    "/ci/",
    "/packages/",
];

pub(crate) const DEV_APP_ROLE_SIGNALS: &[&str] = &[
    "terminal",
    "powershell",
    "command prompt",
    "cmd.exe",
    "shell",
    "console",
    " git",
    "studio",
    "editor",
    " ide",
    "vim",
    "emacs",
    "debug",
    "compiler",
    "docker",
    "kubernetes",
    "kubectl",
    "cargo",
    "webpack",
    "vite",
    "node.js",
];

pub(crate) const COMMUNICATION_PHRASES: &[&str] = &[
    "inbox",
    "outbox",
    "unread",
    "compose",
    "e-mail",
    "email",
    "nachricht",
    "chat",
    "meeting",
    "standup",
    "stand-up",
    "huddle",
    "video call",
    "voice call",
    "waiting room",
    "calendar invite",
    "einladung",
    "teams-besprechung",
    "zoom meeting",
];

pub(crate) const COMMUNICATION_APP_SIGNALS: &[&str] = &[
    "mail",
    "posteingang",
    "outlook",
    "thunderbird",
    "chat",
    "teams",
    "zoom",
    "meet",
    "skype",
    "telegram",
    "whatsapp",
    "signal",
    "discord",
    "slack",
    "kalender",
    "calendar",
];

pub(crate) const ORGANIZATION_PHRASES: &[&str] = &[
    "sprint",
    "backlog",
    "kanban",
    "roadmap",
    "milestone",
    "issue tracker",
    "project board",
    "task board",
    "to-do",
    "todo",
    "checklist",
    "planner",
    "zeiterfassung",
    "time tracking",
];

pub(crate) const ORGANIZATION_APP_SIGNALS: &[&str] = &[
    "explorer",
    "finder",
    "datei-explorer",
    "files",
    "pdf",
    "acrobat",
    "word",
    "excel",
    "powerpoint",
    "sheets",
    "slides",
    "keynote",
    "pages",
    "numbers",
    "figma",
    "miro",
    "whiteboard",
    "notizen",
    "notes",
    "notion",
    "obsidian",
    "logseq",
    "evernote",
    "onenote",
    "trello",
    "asana",
    "jira",
    "confluence",
    "linear",
    "clickup",
    "todoist",
];

pub(crate) const RESEARCH_PHRASES: &[&str] = &[
    "documentation",
    "dokumentation",
    "tutorial",
    "anleitung",
    "guide",
    "handbook",
    "reference",
    "api reference",
    "getting started",
    "how to",
    "wie man",
    "was ist",
    "erklärung",
    "learn ",
    " lernen",
    "course",
    "kurs",
    "specification",
    "spezifikation",
    "whitepaper",
    " wiki",
    "artikel",
    " blog",
    " docs",
    "manual",
    "handbuch",
    "faq",
    "cheatsheet",
];

pub(crate) const OFFICE_DOC_EXTENSIONS: &[&str] =
    &[".pdf", ".doc", ".docx", ".xls", ".xlsx", ".ppt", ".pptx"];

pub(crate) const ENTERTAINMENT_PHRASES: &[&str] = &[
    "livestream",
    "live stream",
    "gameplay",
    "gaming",
    "playthrough",
    "speedrun",
    "playlist",
    "podcast",
    "soundtrack",
    "trailer",
    "episode",
    "season ",
    "serie",
    "film",
    "movie",
    "anime",
    "streamt",
    "jetzt live",
    "now playing",
    "hoerspiel",
    "hörspiel",
];

pub(crate) const ENTERTAINMENT_APP_SIGNALS: &[&str] = &[
    "steam",
    "epic games",
    "vlc",
    "media player",
    "xbox",
    "playstation",
    "nintendo",
    "gog galaxy",
    "battle.net",
];

pub(crate) const ENTERTAINMENT_URL_MARKERS: &[&str] = &[
    "/watch",
    "/track/",
    "/album/",
    "/videos/",
    "/video/",
    "/shorts/",
    "/playlist",
    "/live/",
    "/stream/",
    "/episode/",
    "/serien/",
    "/movies/",
];

pub(crate) const MEDIA_PLATFORM_KEYWORDS: &[&str] = &[
    "video", "stream", "music", "podcast", "radio", "anime", "film", "serie", "tv",
];

pub(crate) const SHOPPING_PHRASES: &[&str] = &[
    "warenkorb",
    "shopping cart",
    "checkout",
    "bestellung",
    "order confirmation",
    "lieferung",
    "produktdetails",
    "product details",
    "add to cart",
    "in den warenkorb",
    "jetzt kaufen",
    "buy now",
    "sale",
    "rabatt",
    "angebot",
    "preisvergleich",
];

pub(crate) const SHOPPING_APP_MARKERS: &[&str] = &[" store", " marketplace"];

pub(crate) const SHOPPING_URL_MARKERS: &[&str] = &[
    "/product/",
    "/products/",
    "/cart",
    "/basket",
    "/checkout",
    "/shop/",
    "/order/",
];

pub(crate) const SHOPPING_APP_FALSE_POSITIVES: &[&str] = &["photoshop", "workshop", "snapshop"];

pub(crate) const SYSTEM_PHRASES: &[&str] = &[
    "settings",
    "einstellungen",
    "control panel",
    "systemsteuerung",
    "task manager",
    "aufgabenverwaltung",
    "geräte-manager",
    "device manager",
    "windows update",
    "system configuration",
    "system preferences",
    "installer",
    "installation",
    "setup wizard",
    "registry editor",
    "disk management",
    "datenträgerverwaltung",
    "sicherheit",
    "security center",
];

pub(crate) const SYSTEM_APP_SIGNALS: &[&str] = &[
    "settings",
    "einstellungen",
    "systemsteuerung",
    "task manager",
    "aufgabenverwaltung",
    "geräte-manager",
    "device manager",
    "registry",
    "installer",
    "windows update",
    "control panel",
];
